Repository acacode/swagger-typescript-api, pull requests merged in 2025-03, with the labels that each got.

#1064 Fix route param parsing when the param begins with just one letter (rebased original PR #686 by @ahoseinian)
  .changeset/honest-bears-stay.md
  src/schema-routes/schema-routes.ts
  tests/spec/extractRequestParams/__snapshots__/basic.test.ts.snap
  tests/spec/extractRequestParams/schema.json
Labels: bug

#1100 Feature more info about extracted types
  .changeset/loose-lies-fetch.md
  src/configuration.ts
  src/schema-components-map.ts
  src/schema-parser/schema-parser-fabric.ts
  src/schema-routes/schema-routes.ts
  types/index.ts
Labels: enhancement

#1101 Fix CLI executable by adding the required shebang to the entry file
  .changeset/free-chairs-film.md
  index.ts
Labels: bug

#1106 Fix CLI argument definitions and client generation logic
  .changeset/early-kings-marry.md
  .changeset/easy-paths-check.md
  .changeset/moody-dodos-brake.md
  index.ts
Labels: bug

#1108 Fix default value for `no-client` argument in command configuration
  .changeset/easy-paths-check.md
  .changeset/five-moles-wonder.md
  index.ts
Labels: bug

#1051 Fix missing request type
  .changeset/clear-houses-tease.md
  src/swagger-schema-resolver.ts
  tests/__snapshots__/extended.test.ts.snap
  tests/__snapshots__/simple.test.ts.snap
  tests/spec/axios/__snapshots__/basic.test.ts.snap
  tests/spec/axiosSingleHttpClient/__snapshots__/basic.test.ts.snap
  tests/spec/extractRequestBody/__snapshots__/basic.test.ts.snap
  tests/spec/js/__snapshots__/basic.test.ts.snap
  tests/spec/jsAxios/__snapshots__/basic.test.ts.snap
  tests/spec/patch/__snapshots__/basic.test.ts.snap
  tests/spec/sortTypes-false/__snapshots__/basic.test.ts.snap
  tests/spec/sortTypes/__snapshots__/basic.test.ts.snap
  tests/spec/typeSuffixPrefix/__snapshots__/basic.test.ts.snap
Labels: bug, enhancement

#1069 Fix parameter name to fileName
  .changeset/stupid-walls-act.md
  README.md
  types/index.ts
Labels: bug, documentation

#1118 Fix default value for `no-client` option in `generateCommand` to `false`
  .changeset/dark-memes-help.md
  index.ts
Labels: bug

#1141 Remove redundant `union-enums` option in favor of `generate-union-enums`
  .changeset/weak-lemons-buy.md
  README.md
  index.ts
  tests/spec/unionEnums/__snapshots__/basic.test.ts.snap
  tests/spec/unionEnums/basic.test.ts
Labels: bug, documentation

#1144 Use `c12` for wider configuration file format support
  .changeset/fancy-actors-wait.md
  index.ts
  package.json
  yarn.lock
Labels: enhancement

#1149 Re-add TypeScript definitions for better type support
  package.json
  tsup.config.ts
Labels: enhancement
