Repository acacode/swagger-typescript-api, pull requests merged in 2025-08, with the labels that each got.

#1008 Fix handling of input of type FormData for the Fetch client
  .changeset/loud-dancers-shake.md
  templates/base/http-clients/fetch-http-client.ejs
  tests/__snapshots__/extended.test.ts.snap
  tests/__snapshots__/simple.test.ts.snap
  tests/spec/another-query-params/__snapshots__/basic.test.ts.snap
  tests/spec/custom-extensions/__snapshots__/basic.test.ts.snap
  tests/spec/defaultAsSuccess/__snapshots__/basic.test.ts.snap
  tests/spec/defaultResponse/__snapshots__/basic.test.ts.snap
  tests/spec/deprecated/__snapshots__/basic.test.ts.snap
  tests/spec/dot-path-params/__snapshots__/basic.test.ts.snap
  tests/spec/enumNamesAsValues/__snapshots__/basic.test.ts.snap
  tests/spec/enumNotFirstInComponents/__snapshots__/basic.test.ts.snap
  tests/spec/extractRequestBody/__snapshots__/basic.test.ts.snap
  tests/spec/extractRequestParams/__snapshots__/basic.test.ts.snap
  tests/spec/extractResponseBody/__snapshots__/basic.test.ts.snap
  tests/spec/extractResponseError/__snapshots__/basic.test.ts.snap
  tests/spec/jsAxios/__snapshots__/basic.test.ts.snap
  tests/spec/jsonapi-media-type/__snapshots__/basic.test.ts.snap
  tests/spec/moduleNameFirstTag/__snapshots__/basic.test.ts.snap
  tests/spec/moduleNameIndex/__snapshots__/basic.test.ts.snap
  tests/spec/on-insert-path-param/__snapshots__/basic.test.ts.snap
  tests/spec/operationId-starting-with-number/__snapshots__/basic.test.ts.snap
  tests/spec/patch/__snapshots__/basic.test.ts.snap
  tests/spec/responses/__snapshots__/basic.test.ts.snap
  tests/spec/singleHttpClient/__snapshots__/basic.test.ts.snap
  tests/spec/sortTypes-false/__snapshots__/basic.test.ts.snap
  tests/spec/sortTypes/__snapshots__/basic.test.ts.snap
  tests/spec/typeSuffixPrefix/__snapshots__/basic.test.ts.snap
  tests/spec/unionEnums/__snapshots__/basic.test.ts.snap
Labels: bug

#1376 Merge GenerateApiParamsBase into configuration
  .changeset/merge-generate-api-types.md
  .changeset/reinstate-modular-flag.md
  types/index.ts
Labels: codex

#1378 Allow partial extractingOptions in generateApi configuration
  .changeset/partial-extracting-options.md
  types/index.ts
Labels: codex

#1380 Ensure anyOf preserves primitive types
  .changeset/primitive-anyof-test.md
  tests/spec/object-types/__snapshots__/basic.test.ts.snap
  tests/spec/object-types/schema.json
Labels: codex

#1382 Fix enum value quoting for mismatched schema types
  .changeset/fix-enum-quotation.md
  src/schema-parser/base-schema-parsers/enum.ts
  tests/__snapshots__/extended.test.ts.snap
  tests/__snapshots__/simple.test.ts.snap
  tests/fixtures/schemas/v3.0/enum-type-mismatch.yaml
Labels: bug, codex

#1385 Avoid response cloning in fetch HTTP client to prevent memory leaks
  .changeset/fix-response-clone-leak.md
  templates/base/http-clients/fetch-http-client.ejs
  tests/__snapshots__/extended.test.ts.snap
  tests/__snapshots__/simple.test.ts.snap
  tests/spec/another-query-params/__snapshots__/basic.test.ts.snap
  tests/spec/custom-extensions/__snapshots__/basic.test.ts.snap
  tests/spec/defaultAsSuccess/__snapshots__/basic.test.ts.snap
  tests/spec/defaultResponse/__snapshots__/basic.test.ts.snap
  tests/spec/deprecated/__snapshots__/basic.test.ts.snap
  tests/spec/dot-path-params/__snapshots__/basic.test.ts.snap
  tests/spec/enumNamesAsValues/__snapshots__/basic.test.ts.snap
  tests/spec/enumNamesAsValues/__snapshots__/inline.test.ts.snap
  tests/spec/enumNotFirstInComponents/__snapshots__/basic.test.ts.snap
  tests/spec/extractRequestBody/__snapshots__/basic.test.ts.snap
  tests/spec/extractRequestParams/__snapshots__/basic.test.ts.snap
  tests/spec/extractResponseBody/__snapshots__/basic.test.ts.snap
  tests/spec/extractResponseError/__snapshots__/basic.test.ts.snap
  tests/spec/jsAxios/__snapshots__/basic.test.ts.snap
  tests/spec/jsonapi-media-type/__snapshots__/basic.test.ts.snap
  tests/spec/moduleNameFirstTag/__snapshots__/basic.test.ts.snap
  tests/spec/moduleNameIndex/__snapshots__/basic.test.ts.snap
  tests/spec/on-insert-path-param/__snapshots__/basic.test.ts.snap
  tests/spec/operationId-starting-with-number/__snapshots__/basic.test.ts.snap
  tests/spec/patch/__snapshots__/basic.test.ts.snap
  tests/spec/responses/__snapshots__/basic.test.ts.snap
  tests/spec/singleHttpClient/__snapshots__/basic.test.ts.snap
  tests/spec/sortTypes-false/__snapshots__/basic.test.ts.snap
  tests/spec/sortTypes/__snapshots__/basic.test.ts.snap
  tests/spec/typeSuffixPrefix/__snapshots__/basic.test.ts.snap
  tests/spec/unionEnums/__snapshots__/basic.test.ts.snap
Labels: bug, codex
